-- Saisie complete des 5 sections ajoutees par la revue client (V10) pour les
-- 5 directions : elles etaient restees NOT_STARTED et sans contenu, ce qui laissait
-- autant de trous dans le document consolide PSD 2027-2031.
--
--   S01B (19) Analyse des performances de l'annee 2026
--   S03B (20) Synthese de l'analyse des ressources
--   S06B (21) Synthese des enjeux et des contraintes
--   S09B (22) Synthese du cadre logique
--   S14B (23) Plan d'evolution des effectifs
--
-- Le contenu suit la meme logique que les seeds V7/V9 : il est coherent avec les
-- sections deja saisies de chaque direction (matrice des ressources S02, SWOT S04,
-- axes S08, fiche d'indicateurs S13) et ne porte que les champs de saisie. Les
-- champs calcules (taux S01B, rappel de la matrice S03B, axes S09B, totaux S14B)
-- restent produits a la lecture par DerivedFieldsService.

-- ---- S01B (section 19) ----
INSERT INTO section_responses (group_id, section_id, content_json, version, updated_by) VALUES
(1, 19, '{"rows":[{"domain":"Ventes et chiffre d''affaires","indicator":"Chiffre d''affaires commercial annuel (millions FCFA)","target2026":4200,"achieved2026":3980,"comment":"Ecart de 220 MFCFA concentre sur le segment entreprises : la croissance du courrier de gestion n''a pas compense le recul du courrier classique"},{"domain":"Reseau commercial","indicator":"Nombre de nouveaux points de vente ouverts","target2026":12,"achieved2026":9,"comment":"Trois ouvertures reportees en 2027 faute de locaux disponibles dans les zones ciblees"},{"domain":"Relation client","indicator":"Taux de satisfaction client (%)","target2026":85,"achieved2026":78,"comment":"Insatisfaction principalement liee aux delais de livraison, hors perimetre direct de la direction"},{"domain":"Relation client","indicator":"Taux de fidelisation de la clientele (%)","target2026":80,"achieved2026":74,"comment":"Erosion sur les petits comptes ; les grands comptes sont restes stables"},{"domain":"Digitalisation commerciale","indicator":"Taux de couverture CRM de la force de vente (%)","target2026":60,"achieved2026":35,"comment":"Deploiement du CRM decale au second semestre ; la formation des commerciaux reste a achever"},{"domain":"Marketing et communication","indicator":"Nombre de campagnes commerciales realisees","target2026":8,"achieved2026":6,"comment":"Deux campagnes annulees par arbitrage budgetaire en fin d''exercice"}]}', 1, 2),
(2, 19, '{"rows":[{"domain":"Acheminement","indicator":"Delai moyen d''acheminement (jours)","target2026":3,"achieved2026":3.8,"comment":"Objectif non atteint : pannes repetees sur les vehicules de liaison inter-regionale"},{"domain":"Parc et equipements","indicator":"Taux de disponibilite du parc de vehicules (%)","target2026":90,"achieved2026":82,"comment":"Immobilisations plus longues que prevu, faute de pieces detachees en stock"},{"domain":"Maintenance","indicator":"Taux de realisation du plan de maintenance preventive (%)","target2026":85,"achieved2026":68,"comment":"La maintenance corrective a mobilise les equipes au detriment du preventif"},{"domain":"Continuite de service","indicator":"Nombre d''incidents techniques majeurs","target2026":10,"achieved2026":17,"comment":"Sept incidents de plus que la cible, dont onze sur des equipements de plus de quinze ans"},{"domain":"Conformite technique","indicator":"Taux de conformite des installations aux normes (%)","target2026":95,"achieved2026":88,"comment":"Non-conformites residuelles sur trois sites regionaux, mise a niveau programmee en 2027"},{"domain":"Exploitation","indicator":"Taux de couverture des sites par le suivi des flux (%)","target2026":70,"achieved2026":45,"comment":"Interconnexion des systemes de suivi limitee aux sites de Dakar et de Thies"}]}', 1, 3),
(3, 19, '{"rows":[{"domain":"Comptabilite","indicator":"Delai moyen de cloture comptable mensuelle (jours)","target2026":10,"achieved2026":15,"comment":"Cloture ralentie par les remontees tardives des directions operationnelles"},{"domain":"Budget","indicator":"Ecart budget-realisations (%)","target2026":5,"achieved2026":9,"comment":"Ecart tire par les charges de maintenance et de carburant, sous-estimees au budget initial"},{"domain":"Tresorerie","indicator":"Delai moyen de paiement des fournisseurs (jours)","target2026":45,"achieved2026":62,"comment":"Tension de tresorerie au troisieme trimestre ; le circuit de validation reste trop long"},{"domain":"Financement","indicator":"Montant des financements mobilises (millions FCFA)","target2026":1500,"achieved2026":1100,"comment":"Une ligne de financement partenaire n''a pas abouti dans l''exercice"},{"domain":"Recouvrement","indicator":"Taux de recouvrement des creances (%)","target2026":85,"achieved2026":76,"comment":"Creances anciennes sur le segment public toujours non apurees"},{"domain":"Controle interne","indicator":"Taux de couverture de la cartographie des risques (%)","target2026":80,"achieved2026":55,"comment":"Cartographie realisee sur les processus financiers, pas encore etendue aux processus operationnels"}]}', 1, 4),
(4, 19, '{"rows":[{"domain":"Infrastructure SI","indicator":"Taux de disponibilite des systemes critiques (%)","target2026":99,"achieved2026":96.5,"comment":"Deux interruptions majeures liees a l''alimentation electrique de la salle serveurs"},{"domain":"Cybersecurite","indicator":"Nombre d''incidents de securite detectes","target2026":5,"achieved2026":12,"comment":"Hausse des tentatives d''hameconnage ; aucun incident n''a entraine de perte de donnees"},{"domain":"Gouvernance SI","indicator":"Taux d''avancement du schema directeur SI (%)","target2026":60,"achieved2026":40,"comment":"Retard sur le chantier d''urbanisation, faute d''arbitrage budgetaire pluriannuel"},{"domain":"Support utilisateurs","indicator":"Taux de satisfaction des utilisateurs internes du support (%)","target2026":85,"achieved2026":81,"comment":"Delais de resolution corrects, insatisfaction residuelle sur le renouvellement du materiel"},{"domain":"Competences numeriques","indicator":"Part des agents formes aux competences numeriques (%)","target2026":50,"achieved2026":32,"comment":"Plan de formation engage en fin d''exercice seulement"},{"domain":"Digitalisation des services","indicator":"Nombre de services metier digitalises","target2026":6,"achieved2026":4,"comment":"Deux projets reportes en attendant la refonte du socle applicatif"}]}', 1, 5),
(5, 19, '{"rows":[{"domain":"Acheminement","indicator":"Delai moyen d''acheminement du courrier et des colis (jours)","target2026":3,"achieved2026":4.2,"comment":"Delais degrades sur les axes secondaires : tournees non optimisees et sous-effectif de chauffeurs"},{"domain":"Parc de vehicules","indicator":"Taux de disponibilite du parc de vehicules (%)","target2026":88,"achieved2026":74,"comment":"Parc vieillissant : l''age moyen des vehicules depasse douze ans sur les liaisons regionales"},{"domain":"Centres de tri","indicator":"Volume de colis traites (milliers)","target2026":950,"achieved2026":1080,"comment":"Cible depassee grace a la croissance du e-commerce, mais au prix d''une saturation des centres de tri"},{"domain":"Couts logistiques","indicator":"Cout logistique unitaire (FCFA par colis)","target2026":750,"achieved2026":910,"comment":"Surcout lie au carburant et au recours accru a la sous-traitance en periode de pointe"},{"domain":"Maillage territorial","indicator":"Taux de couverture territoriale des points de collecte (%)","target2026":80,"achieved2026":68,"comment":"Trois regions restent insuffisamment couvertes, notamment a l''est du pays"},{"domain":"Qualite de service","indicator":"Taux de satisfaction sur les delais de livraison (%)","target2026":80,"achieved2026":65,"comment":"Premier motif de reclamation client sur l''exercice ; absence d''information de suivi en temps reel"}]}', 1, 6)
AS nouvelle
ON DUPLICATE KEY UPDATE content_json = nouvelle.content_json, version = section_responses.version + 1, updated_by = nouvelle.updated_by;

-- ---- S03B (section 20) ----
INSERT INTO section_responses (group_id, section_id, content_json, version, updated_by) VALUES
(1, 20, '{"synthesisNote":"La matrice des ressources fait ressortir une direction commerciale solide par son capital de marque et l''etendue de son reseau, mais freinee par des moyens de pilotage et des outils de vente en retard sur l''evolution du marche. Les forces relevent principalement du capital relationnel et de la couverture territoriale ; les faiblesses se concentrent sur l''outillage numerique, le budget de conquete et la mesure de la performance. Les defis prioritaires retenus pour le PSD 2027-2031 visent donc a transformer cette presence historique en avantage concurrentiel durable.","majorStrengths":["Notoriete de la marque et confiance historique de la clientele","Reseau commercial couvrant l''ensemble du territoire national","Gamme de services diversifiee (courrier, colis, services financiers)","Equipes de vente experimentees et bien implantees localement"],"majorWeaknesses":["Systeme d''information commercial vieillissant, sans CRM operationnel","Budget marketing et de conquete insuffisant au regard des objectifs","Faible presence sur les canaux digitaux et le e-commerce","Absence de tableau de bord commercial partage et de pilotage par indicateurs"],"priorityChallenges":["Deployer un CRM et des outils d''aide a la vente sur l''ensemble du reseau","Se differencier par la qualite de service et la proximite client","Renforcer la presence commerciale sur les canaux digitaux","Instaurer un pilotage commercial par indicateurs partages","Former et fideliser les equipes de vente sur les nouveaux canaux"]}', 1, 2),
(2, 20, '{"synthesisNote":"L''analyse des ressources techniques met en evidence un savoir-faire operationnel reel et une couverture nationale complete, mais adosses a des infrastructures et a un parc dont le vieillissement pese directement sur la continuite de service. La maintenance reste majoritairement corrective et les systemes de suivi des flux ne sont interconnectes que partiellement. Les defis prioritaires portent donc sur l''investissement, le passage au preventif et l''industrialisation du pilotage technique.","majorStrengths":["Couverture technique de l''ensemble du territoire national","Savoir-faire operationnel reconnu et agents techniques experimentes","Procedures d''exploitation etablies sur les sites principaux","Capacite d''intervention de proximite dans toutes les regions"],"majorWeaknesses":["Vieillissement des infrastructures et du parc technique","Maintenance encore majoritairement reactive plutot que preventive","Interconnexion limitee des systemes de suivi entre les sites","Absence d''enveloppe budgetaire pluriannuelle securisee pour la maintenance"],"priorityChallenges":["Engager un programme pluriannuel d''investissement dans les infrastructures","Basculer vers une maintenance preventive planifiee et suivie","Interconnecter les systemes de suivi des flux sur tous les sites","Securiser les stocks de pieces detachees critiques","Generaliser le suivi des indicateurs techniques a l''ensemble des sites"]}', 1, 3),
(3, 20, '{"synthesisNote":"La direction financiere dispose d''une equipe qualifiee et d''un cadre de gestion conforme aux normes, mais son fonctionnement reste marque par des delais de traitement longs et un pilotage encore largement retrospectif. Les ecarts recurrents entre budget et realisations, comme les tensions de tresorerie constatees en 2026, traduisent un besoin de previsionnel et d''outillage. Les defis prioritaires visent a passer d''une comptabilite de constat a un pilotage financier anticipatif.","majorStrengths":["Equipe financiere qualifiee et experimentee","Processus budgetaire annuel etabli et respecte","Conformite aux normes comptables en vigueur","Dispositif de controle interne existant sur les processus financiers"],"majorWeaknesses":["Delais de cloture comptable et de reporting trop longs","Ecarts frequents entre previsions budgetaires et realisations","Outils de gestion financiere partiellement modernises et peu interconnectes","Cartographie des risques financiers incomplete"],"priorityChallenges":["Reduire les delais de cloture et de reporting financier","Passer a un pilotage financier previsionnel et trimestriel","Interconnecter le systeme financier aux applications metier","Diversifier et securiser les sources de financement","Renforcer la cartographie et le suivi des risques financiers"]}', 1, 4),
(4, 20, '{"synthesisNote":"Le systeme d''information repose sur une equipe technique motivee et sur des applications metier deja diffusees dans les directions, mais il souffre d''un socle heterogene et d''une gouvernance encore incomplete. L''exposition aux cybermenaces s''accroit plus vite que les moyens de protection, et l''absence de budget pluriannuel freine l''execution du schema directeur. Les defis prioritaires portent sur l''urbanisation du SI, la securite et la montee en competences.","majorStrengths":["Equipe SI technique, polyvalente et motivee","Applications metier deja deployees dans l''ensemble des directions","Bonne reactivite du support aux utilisateurs internes","Existence d''un schema directeur SI servant de cadre de reference"],"majorWeaknesses":["Infrastructure informatique vieillissante sur plusieurs composants critiques","Systemes heterogenes et faiblement interconnectes","Gouvernance des donnees non formalisee","Absence de budget pluriannuel securise pour les projets SI"],"priorityChallenges":["Urbaniser et interconnecter le systeme d''information","Deployer un dispositif de cybersecurite renforce","Moderniser l''infrastructure informatique centrale","Formaliser une politique de gouvernance des donnees","Former les equipes aux technologies cloud et a la cybersecurite"]}', 1, 5),
(5, 20, '{"synthesisNote":"La direction logistique s''appuie sur un maillage national de centres de tri et sur des equipes experimentees, mais son outil de production est fragilise par un parc de vehicules vieillissant et par l''absence d''outil de planification des tournees. La croissance des volumes de colis liee au e-commerce accentue la pression sur des moyens deja tendus. Les defis prioritaires visent la modernisation du parc et l''industrialisation de la planification logistique.","majorStrengths":["Reseau de centres de tri couvrant l''ensemble du territoire national","Chauffeurs et agents de tri experimentes","Couverture logistique nationale historique","Bonne coordination avec les Directions Commerciale et Technique"],"majorWeaknesses":["Vieillissement du parc de vehicules de transport","Absence d''outil de planification et de suivi des tournees","Delais d''acheminement superieurs a ceux de la concurrence","Sous-effectif de chauffeurs dans plusieurs zones"],"priorityChallenges":["Moderniser et renouveler le parc de vehicules","Deployer un outil de planification logistique integre","Reduire les delais d''acheminement pour rester competitif","Renforcer les effectifs logistiques la ou la demande croit","Affiner le suivi analytique des couts logistiques par tournee"]}', 1, 6)
AS nouvelle
ON DUPLICATE KEY UPDATE content_json = nouvelle.content_json, version = section_responses.version + 1, updated_by = nouvelle.updated_by;

-- ---- S06B (section 21) ----
INSERT INTO section_responses (group_id, section_id, content_json, version, updated_by) VALUES
(1, 21, '{"rows":[{"domain":"Courrier et colis","constraints":["Recul structurel des volumes de courrier classique","Pression tarifaire des operateurs prives sur les segments rentables","Qualite de service dependante des delais d''acheminement"],"challenges":["Compenser le recul du courrier par la croissance du colis","Construire une offre differenciante sur la proximite et la fiabilite"]},{"domain":"Services financiers","constraints":["Concurrence des etablissements de paiement et des operateurs mobiles","Cadre reglementaire exigeant sur les operations financieres"],"challenges":["Faire du reseau d''agences un canal privilegie d''inclusion financiere","Elargir la gamme de services financiers de proximite"]},{"domain":"Grands comptes et entreprises","constraints":["Cycles de decision longs et exigences contractuelles elevees","Faible outillage de suivi de la relation grands comptes"],"challenges":["Structurer une demarche grands comptes dediee","Securiser et developper le courrier de gestion des entreprises"]},{"domain":"Reseau d''agences et points de vente","constraints":["Locaux et equipements inegalement modernises selon les regions","Difficulte a trouver des emplacements dans les zones a fort potentiel"],"challenges":["Moderniser progressivement le reseau commercial","Etendre la couverture dans les zones a fort potentiel"]},{"domain":"Vente en ligne et canaux digitaux","constraints":["Faible presence sur les canaux digitaux","Absence de CRM operationnel et de parcours de vente en ligne"],"challenges":["Deployer un CRM et des outils d''aide a la vente","Capter la croissance du e-commerce et de la livraison"]}]}', 1, 2),
(2, 21, '{"rows":[{"domain":"Infrastructures et batiments techniques","constraints":["Vieillissement des installations sur plusieurs sites regionaux","Non-conformites residuelles aux normes techniques et de securite"],"challenges":["Engager un programme pluriannuel de mise a niveau des infrastructures","Atteindre la conformite complete des installations aux normes"]},{"domain":"Parc de vehicules et equipements","constraints":["Age moyen eleve du parc et immobilisations frequentes","Ruptures de stock sur les pieces detachees critiques"],"challenges":["Renouveler progressivement le parc technique","Securiser un stock de pieces detachees critiques"]},{"domain":"Maintenance et continuite de service","constraints":["Predominance de la maintenance corrective sur le preventif","Incidents techniques majeurs superieurs a la cible"],"challenges":["Generaliser la maintenance preventive planifiee","Reduire durablement le nombre d''incidents majeurs"]},{"domain":"Exploitation et suivi des flux","constraints":["Interconnexion des systemes de suivi limitee a quelques sites","Circuits de tri et d''acheminement insuffisamment optimises"],"challenges":["Interconnecter les systemes de suivi sur l''ensemble des sites","Optimiser les circuits de tri et d''acheminement"]},{"domain":"Securite et conformite technique","constraints":["Exigences reglementaires techniques croissantes","Formation technique continue insuffisamment structuree"],"challenges":["Structurer un plan de formation technique continue","Anticiper l''evolution des normes techniques applicables"]}]}', 1, 3),
(3, 21, '{"rows":[{"domain":"Gestion budgetaire","constraints":["Ecarts recurrents entre previsions et realisations","Arbitrages budgetaires contraints par le contexte inflationniste"],"challenges":["Ameliorer la qualite des previsions et le controle budgetaire","Prioriser les depenses au regard des axes du plan strategique"]},{"domain":"Comptabilite et reporting","constraints":["Delais de cloture mensuelle superieurs aux standards","Remontees d''informations tardives des directions operationnelles"],"challenges":["Reduire les delais de cloture et de reporting","Fiabiliser la chaine de remontee des informations comptables"]},{"domain":"Tresorerie et paiements","constraints":["Tensions de tresorerie sur une partie de l''exercice","Circuit de validation des paiements trop long"],"challenges":["Ramener le delai de paiement fournisseurs dans les termes contractuels","Optimiser le circuit de traitement des paiements"]},{"domain":"Financement et investissement","constraints":["Dependance forte aux ressources propres","Financements partenaires non securises a moyen terme"],"challenges":["Diversifier les sources de financement du plan","Securiser un financement pluriannuel des investissements prioritaires"]},{"domain":"Controle interne et risques","constraints":["Cartographie des risques limitee aux processus financiers","Cyber-risques croissants sur les systemes financiers"],"challenges":["Etendre la cartographie des risques a l''ensemble des processus","Renforcer la securisation des operations financieres"]}]}', 1, 4),
(4, 21, '{"rows":[{"domain":"Infrastructure et exploitation SI","constraints":["Composants d''infrastructure en fin de vie","Dependance a l''alimentation electrique de la salle serveurs"],"challenges":["Moderniser l''infrastructure informatique centrale","Securiser la continuite d''exploitation des systemes critiques"]},{"domain":"Cybersecurite","constraints":["Hausse des tentatives d''hameconnage et des cybermenaces","Dispositif de protection et de detection incomplet"],"challenges":["Deployer un dispositif de cybersecurite renforce","Sensibiliser l''ensemble des agents aux risques numeriques"]},{"domain":"Applications metier et donnees","constraints":["Systemes heterogenes et faiblement interconnectes","Gouvernance des donnees non formalisee"],"challenges":["Urbaniser et interconnecter le systeme d''information","Formaliser une politique de gouvernance des donnees"]},{"domain":"Gouvernance et financement du SI","constraints":["Absence de budget pluriannuel dedie au SI","Retard d''execution du schema directeur"],"challenges":["Securiser un budget pluriannuel pour le SI","Aligner la feuille de route SI sur le plan strategique"]},{"domain":"Competences numeriques","constraints":["Part encore faible d''agents formes aux competences numeriques","Tension sur les profils cloud et cybersecurite"],"challenges":["Former les equipes aux technologies cloud et a la cybersecurite","Accompagner la montee en competences numeriques de toutes les directions"]}]}', 1, 5),
(5, 21, '{"rows":[{"domain":"Transport et acheminement","constraints":["Delais d''acheminement superieurs a ceux de la concurrence","Hausse du prix du carburant et des couts de transport","Tournees non optimisees sur les axes secondaires"],"challenges":["Reduire le delai moyen d''acheminement","Optimiser les tournees et le chargement des vehicules"]},{"domain":"Parc de vehicules","constraints":["Age moyen du parc superieur a douze ans sur les liaisons regionales","Taux de disponibilite du parc en deca de la cible"],"challenges":["Renouveler progressivement le parc de vehicules","Porter la disponibilite du parc au niveau des standards du secteur"]},{"domain":"Centres de tri et entrepots","constraints":["Saturation des centres de tri en periode de pointe","Equipements de tri partiellement automatises"],"challenges":["Renforcer la capacite et le maillage des centres de tri","Moderniser les equipements de tri des principaux centres"]},{"domain":"Logistique du e-commerce et des colis","constraints":["Croissance rapide et saisonniere des volumes de colis","Recours couteux a la sous-traitance en periode de pointe"],"challenges":["Capter la croissance du e-commerce dans des conditions rentables","Encadrer et evaluer la performance des sous-traitants"]},{"domain":"Ressources humaines logistiques","constraints":["Sous-effectif de chauffeurs dans plusieurs zones","Difficulte a recruter et a fideliser des chauffeurs qualifies"],"challenges":["Renforcer les effectifs logistiques la ou la demande croit","Former les equipes aux outils de planification et de suivi"]}]}', 1, 6)
AS nouvelle
ON DUPLICATE KEY UPDATE content_json = nouvelle.content_json, version = section_responses.version + 1, updated_by = nouvelle.updated_by;

-- ---- S09B (section 22) ----
INSERT INTO section_responses (group_id, section_id, content_json, version, updated_by) VALUES
(1, 22, '{"synthesisNote":"La synthese du cadre logique de la Direction Commerciale articule les quatre axes du plan autour d''un impact unique : une entreprise dont la position commerciale est consolidee sur ses marches historiques et etendue aux nouveaux usages. L''axe Croissance commerciale porte l''effet de developpement du chiffre d''affaires, l''axe Excellence operationnelle celui de la qualite de service percue, l''axe Digitalisation la conquete des canaux en ligne et l''axe Capital humain la professionnalisation des equipes de vente. Les extrants sont mesures par les indicateurs de la fiche S13 et les ressources correspondent aux enveloppes inscrites au budget 2027-2031."}', 1, 2),
(2, 22, '{"synthesisNote":"La synthese du cadre logique de la Direction Technique et Exploitation ramene les quatre axes a un impact commun : un outil de production fiable, conforme et disponible sur l''ensemble du territoire. L''axe Fiabilite des infrastructures et l''axe Maintenance preventive portent conjointement l''effet de reduction des incidents majeurs ; l''axe Performance de l''exploitation porte l''effet de reduction des delais d''acheminement ; l''axe Securite et conformite technique securise la conformite reglementaire. Les ressources reposent principalement sur l''enveloppe pluriannuelle d''investissement et de maintenance."}', 1, 3),
(3, 22, '{"synthesisNote":"La synthese du cadre logique de la Direction Financiere et Comptable place en impact la soutenabilite financiere de l''entreprise sur l''horizon du plan. L''axe Soutenabilite financiere et l''axe Mobilisation de financements portent l''effet d''equilibre des ressources ; l''axe Fiabilite comptable porte l''effet de reduction des delais de cloture et de fiabilisation de l''information ; l''axe Optimisation budgetaire porte la maitrise des ecarts entre previsions et realisations. Les intrants correspondent aux moyens humains et aux outils de gestion financiere a moderniser."}', 1, 4),
(4, 22, '{"synthesisNote":"La synthese du cadre logique de la Direction des Systemes d''Information retient comme impact un systeme d''information urbanise, securise et au service des metiers. L''axe Modernisation du SI porte l''effet de disponibilite des systemes critiques, l''axe Cybersecurite l''effet de maitrise des incidents de securite, l''axe Digitalisation des services l''effet d''elargissement des services numeriques offerts aux clients et aux directions, et l''axe Gouvernance et competences SI l''ancrage durable des pratiques. Les ressources dependent de la securisation d''un budget SI pluriannuel."}', 1, 5),
(5, 22, '{"synthesisNote":"La synthese du cadre logique de la Direction Logistique converge vers un impact unique : une chaine logistique fiable, capable d''absorber la croissance des volumes de colis dans des conditions de cout maitrisees. L''axe Modernisation du parc logistique et l''axe Optimisation des tournees portent l''effet de reduction du delai moyen d''acheminement ; l''axe Maillage des centres de tri et entrepots porte l''effet de couverture territoriale ; l''axe Logistique du e-commerce et des colis porte l''effet de captation des nouveaux volumes. Les intrants regroupent les investissements de renouvellement du parc et le deploiement de l''outil de planification."}', 1, 6)
AS nouvelle
ON DUPLICATE KEY UPDATE content_json = nouvelle.content_json, version = section_responses.version + 1, updated_by = nouvelle.updated_by;

-- ---- S14B (section 23) ----
INSERT INTO section_responses (group_id, section_id, content_json, version, updated_by) VALUES
(1, 23, '{"rows":[{"category":"HIERARCHIE","staffKey":"CADRE","label":"","years":{"2027":{"male":18,"female":12},"2028":{"male":20,"female":14},"2029":{"male":22,"female":16},"2030":{"male":24,"female":18},"2031":{"male":26,"female":20}}},{"category":"HIERARCHIE","staffKey":"AGENTS_MAITRISE","label":"","years":{"2027":{"male":30,"female":25},"2028":{"male":32,"female":27},"2029":{"male":34,"female":29},"2030":{"male":36,"female":31},"2031":{"male":38,"female":33}}},{"category":"HIERARCHIE","staffKey":"EMPLOYE","label":"","years":{"2027":{"male":45,"female":40},"2028":{"male":46,"female":42},"2029":{"male":47,"female":43},"2030":{"male":48,"female":44},"2031":{"male":49,"female":45}}},{"category":"HIERARCHIE","staffKey":"JOURNALIER","label":"","years":{"2027":{"male":10,"female":8},"2028":{"male":10,"female":8},"2029":{"male":9,"female":7},"2030":{"male":8,"female":6},"2031":{"male":7,"female":5}}},{"category":"STATUT","staffKey":"CDI","label":"","years":{"2027":{"male":85,"female":71},"2028":{"male":89,"female":76},"2029":{"male":92,"female":79},"2030":{"male":96,"female":82},"2031":{"male":99,"female":86}}},{"category":"STATUT","staffKey":"CDD","label":"","years":{"2027":{"male":16,"female":13},"2028":{"male":17,"female":14},"2029":{"male":18,"female":15},"2030":{"male":18,"female":16},"2031":{"male":19,"female":16}}},{"category":"STATUT","staffKey":"EXPATRIE","label":"","years":{"2027":{"male":2,"female":1},"2028":{"male":2,"female":1},"2029":{"male":2,"female":1},"2030":{"male":2,"female":1},"2031":{"male":2,"female":1}}}]}', 1, 2),
(2, 23, '{"rows":[{"category":"HIERARCHIE","staffKey":"CADRE","label":"","years":{"2027":{"male":26,"female":6},"2028":{"male":28,"female":7},"2029":{"male":30,"female":9},"2030":{"male":32,"female":11},"2031":{"male":34,"female":13}}},{"category":"HIERARCHIE","staffKey":"AGENTS_MAITRISE","label":"","years":{"2027":{"male":58,"female":14},"2028":{"male":60,"female":16},"2029":{"male":62,"female":18},"2030":{"male":64,"female":20},"2031":{"male":66,"female":22}}},{"category":"HIERARCHIE","staffKey":"EMPLOYE","label":"","years":{"2027":{"male":96,"female":22},"2028":{"male":97,"female":24},"2029":{"male":98,"female":26},"2030":{"male":99,"female":28},"2031":{"male":100,"female":30}}},{"category":"HIERARCHIE","staffKey":"JOURNALIER","label":"","years":{"2027":{"male":24,"female":5},"2028":{"male":23,"female":5},"2029":{"male":21,"female":4},"2030":{"male":19,"female":4},"2031":{"male":17,"female":3}}},{"category":"STATUT","staffKey":"CDI","label":"","years":{"2027":{"male":169,"female":39},"2028":{"male":172,"female":44},"2029":{"male":175,"female":48},"2030":{"male":177,"female":53},"2031":{"male":180,"female":57}}},{"category":"STATUT","staffKey":"CDD","label":"","years":{"2027":{"male":32,"female":8},"2028":{"male":33,"female":8},"2029":{"male":33,"female":9},"2030":{"male":34,"female":10},"2031":{"male":34,"female":11}}},{"category":"STATUT","staffKey":"EXPATRIE","label":"","years":{"2027":{"male":3,"female":0},"2028":{"male":3,"female":0},"2029":{"male":3,"female":0},"2030":{"male":3,"female":0},"2031":{"male":3,"female":0}}}]}', 1, 3),
(3, 23, '{"rows":[{"category":"HIERARCHIE","staffKey":"CADRE","label":"","years":{"2027":{"male":12,"female":10},"2028":{"male":13,"female":11},"2029":{"male":14,"female":13},"2030":{"male":15,"female":14},"2031":{"male":16,"female":16}}},{"category":"HIERARCHIE","staffKey":"AGENTS_MAITRISE","label":"","years":{"2027":{"male":16,"female":18},"2028":{"male":17,"female":19},"2029":{"male":18,"female":20},"2030":{"male":19,"female":21},"2031":{"male":20,"female":22}}},{"category":"HIERARCHIE","staffKey":"EMPLOYE","label":"","years":{"2027":{"male":20,"female":24},"2028":{"male":20,"female":25},"2029":{"male":21,"female":26},"2030":{"male":21,"female":27},"2031":{"male":22,"female":28}}},{"category":"HIERARCHIE","staffKey":"JOURNALIER","label":"","years":{"2027":{"male":3,"female":2},"2028":{"male":3,"female":2},"2029":{"male":2,"female":2},"2030":{"male":2,"female":1},"2031":{"male":2,"female":1}}},{"category":"STATUT","staffKey":"CDI","label":"","years":{"2027":{"male":42,"female":45},"2028":{"male":44,"female":47},"2029":{"male":45,"female":50},"2030":{"male":47,"female":52},"2031":{"male":50,"female":55}}},{"category":"STATUT","staffKey":"CDD","label":"","years":{"2027":{"male":8,"female":8},"2028":{"male":8,"female":9},"2029":{"male":9,"female":10},"2030":{"male":9,"female":10},"2031":{"male":9,"female":11}}},{"category":"STATUT","staffKey":"EXPATRIE","label":"","years":{"2027":{"male":1,"female":1},"2028":{"male":1,"female":1},"2029":{"male":1,"female":1},"2030":{"male":1,"female":1},"2031":{"male":1,"female":1}}}]}', 1, 4),
(4, 23, '{"rows":[{"category":"HIERARCHIE","staffKey":"CADRE","label":"","years":{"2027":{"male":14,"female":6},"2028":{"male":16,"female":8},"2029":{"male":18,"female":10},"2030":{"male":20,"female":12},"2031":{"male":22,"female":14}}},{"category":"HIERARCHIE","staffKey":"AGENTS_MAITRISE","label":"","years":{"2027":{"male":12,"female":7},"2028":{"male":13,"female":8},"2029":{"male":14,"female":9},"2030":{"male":15,"female":10},"2031":{"male":16,"female":11}}},{"category":"HIERARCHIE","staffKey":"EMPLOYE","label":"","years":{"2027":{"male":10,"female":8},"2028":{"male":11,"female":9},"2029":{"male":11,"female":10},"2030":{"male":12,"female":10},"2031":{"male":12,"female":11}}},{"category":"HIERARCHIE","staffKey":"JOURNALIER","label":"","years":{"2027":{"male":2,"female":1},"2028":{"male":2,"female":1},"2029":{"male":2,"female":1},"2030":{"male":1,"female":1},"2031":{"male":1,"female":1}}},{"category":"STATUT","staffKey":"CDI","label":"","years":{"2027":{"male":30,"female":18},"2028":{"male":34,"female":21},"2029":{"male":36,"female":24},"2030":{"male":39,"female":27},"2031":{"male":41,"female":30}}},{"category":"STATUT","staffKey":"CDD","label":"","years":{"2027":{"male":6,"female":3},"2028":{"male":6,"female":4},"2029":{"male":7,"female":5},"2030":{"male":7,"female":5},"2031":{"male":8,"female":6}}},{"category":"STATUT","staffKey":"EXPATRIE","label":"","years":{"2027":{"male":2,"female":1},"2028":{"male":2,"female":1},"2029":{"male":2,"female":1},"2030":{"male":2,"female":1},"2031":{"male":2,"female":1}}}]}', 1, 5),
(5, 23, '{"rows":[{"category":"HIERARCHIE","staffKey":"CADRE","label":"","years":{"2027":{"male":10,"female":4},"2028":{"male":11,"female":5},"2029":{"male":12,"female":6},"2030":{"male":13,"female":8},"2031":{"male":14,"female":10}}},{"category":"HIERARCHIE","staffKey":"AGENTS_MAITRISE","label":"","years":{"2027":{"male":28,"female":9},"2028":{"male":30,"female":11},"2029":{"male":32,"female":13},"2030":{"male":34,"female":15},"2031":{"male":36,"female":17}}},{"category":"HIERARCHIE","staffKey":"EMPLOYE","label":"","years":{"2027":{"male":74,"female":18},"2028":{"male":78,"female":21},"2029":{"male":82,"female":24},"2030":{"male":85,"female":27},"2031":{"male":88,"female":30}}},{"category":"HIERARCHIE","staffKey":"JOURNALIER","label":"","years":{"2027":{"male":30,"female":7},"2028":{"male":29,"female":7},"2029":{"male":27,"female":6},"2030":{"male":25,"female":6},"2031":{"male":23,"female":5}}},{"category":"STATUT","staffKey":"CDI","label":"","years":{"2027":{"male":118,"female":32},"2028":{"male":123,"female":37},"2029":{"male":128,"female":41},"2030":{"male":131,"female":47},"2031":{"male":134,"female":52}}},{"category":"STATUT","staffKey":"CDD","label":"","years":{"2027":{"male":23,"female":6},"2028":{"male":24,"female":7},"2029":{"male":24,"female":8},"2030":{"male":25,"female":9},"2031":{"male":26,"female":10}}},{"category":"STATUT","staffKey":"EXPATRIE","label":"","years":{"2027":{"male":1,"female":0},"2028":{"male":1,"female":0},"2029":{"male":1,"female":0},"2030":{"male":1,"female":0},"2031":{"male":1,"female":0}}}]}', 1, 6)
AS nouvelle
ON DUPLICATE KEY UPDATE content_json = nouvelle.content_json, version = section_responses.version + 1, updated_by = nouvelle.updated_by;

UPDATE group_section_status
SET status = 'VALIDATED', submitted_at = NOW(), validated_at = NOW(), last_activity_at = NOW()
WHERE section_id IN (19, 20, 21, 22, 23);

-- Recette du document consolide : les sections deja soumises par les directions
-- sont validees a leur tour, faute de quoi le document final les ecarterait
-- (message "Section non validee : son contenu n'est pas repris") et le controle
-- de completude n'aurait aucune valeur.
UPDATE group_section_status
SET status = 'VALIDATED', validated_at = NOW()
WHERE status = 'SUBMITTED';
